apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-tables
  namespace: todo-list-app
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: asia-southeast1-docker.pkg.dev/belajar-kubernetes-terraform/backend/todo-list-backend:16
        command: ["npx", "sequelize-cli", "db:migrate"]
        env:
        - name: MYSQL_HOST
          value: "todo-list-mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: todo-list-mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-list-mysql-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: "todo_list_db"
      restartPolicy: OnFailure
  backoffLimit: 4
  ttlSecondsAfterFinished: 100
