version: '3.8'

services:
  frontend:
    build: ./todo-list-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./todo-list-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql  # Nama service mysql di Docker Compose
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_NAME=todo_db
    depends_on:
      - mysql
    command: /bin/bash -c "npx sequelize-cli db:migrate && npm start"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: todo_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql-data:
