apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-backend
  namespace: todo-list-app
  labels:
    role: todo-list-backend
    env: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      role: todo-list-backend
  template:
    metadata:
      labels:
        role: todo-list-backend
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: todo-list-backend
        image: asia-southeast1-docker.pkg.dev/belajar-terraform-kubernetes/backend/todo-list-backend:15
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "todo-list-mysql-service.todo-list-app.svc.cluster.local"  # Fully qualified domain name for service
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: todo-list-mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-list-mysql-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: "todo_list_db"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10  # Slightly longer delay to ensure backend initializes
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 20
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: todo-list-backend-service
  namespace: todo-list-app
  labels:
    role: todo-list-backend
spec:
  selector:
    role: todo-list-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP