apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-list-mysql-init
  namespace: todo-list-app
  labels:
    role: todo-list-mysql
    env: production
data:
  init.sql: |
    CREATE TABLE todos (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL
    );
