apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard-zonal  # Sesuaikan dengan StorageClass yang Anda buat
  resources:
    requests:
      storage: 2Gi
