apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard  # Pastikan ini sesuai dengan StorageClass yang ada
  resources:
    requests:
      storage: 1Gi
