apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-frontend
  namespace: todo-list-app
  labels:
    role: todo-list-frontend
    env: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      role: todo-list-frontend
  template:
    metadata:
      labels:
        role: todo-list-frontend
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: todo-list-frontend
        image: asia-southeast1-docker.pkg.dev/belajar-terraform-kubernetes/frontend/todo-list-frontend:18
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: BACKEND_URL
          value: "http://34.135.238.204:5000/api/todos"
        resources:
          requests:
            memory: "256Mi"
            cpu: "400m"
          limits:
            memory: "512Mi"
            cpu: "800m"

---

apiVersion: v1
kind: Service
metadata:
  name: todo-list-frontend-service
  namespace: todo-list-app
  labels:
    role: todo-list-frontend
spec:
  selector:
    role: todo-list-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer  
