apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-frontend
  namespace: todo-list-app
  labels:
    role: todo-list-frontend
    env: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      role: todo-list-frontend
  template:
    metadata:
      labels:
        role: todo-list-frontend
    spec:
      containers:
      - name: todo-list-frontend
        image: asia-southeast1-docker.pkg.dev/belajar-kubernetes-terraform/frontend/todo-list-frontend:38
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: BACKEND_URL
          value: "http://todo-list-backend-service:5000"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 24
        resources:
          requests:
            memory: "138Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "400m"

---

apiVersion: v1
kind: Service
metadata:
  name: todo-list-frontend-service
  namespace: todo-list-app
  labels:
    role: todo-list-frontend
spec:
  selector:
    role: todo-list-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer  # Sesuaikan tipe service jika ingin mengakses dari luar cluster
