pipeline {
    agent any
    tools {
        nodejs 'nodejs'
        jdk 'jdk'
    }

    environment {
        SCANNER_HOME=tool 'sonar-scanner'
        PROJECT_ID = credentials('PROJECT-ID')
        GCP_GAR_REPO_BE_NAME = credentials('GAR-REPO-BE')
        GCP_REGION = 'asia-southeast1'
        REPO_URL = """${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${GCP_GAR_REPO_BE_NAME}"""
        GITHUB_USERNAME = credentials('github-username')
        GITHUB_EMAIL = credentials('github-email')
        GITHUB_REPO_NAME = credentials('github-repo-name')
        GITHUB_CRED = credentials('github-webhook')
        SONAR_AUTH_TOKEN = credentials('sonar-token')
        IMAGE_NAME = 'todo-list-backend'
    }

    stages {
        stage('Cleaning Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from Git') {
            steps {
                git branch: 'main', 
                    credentialsId: 'github-webhook', 
                    url: 'https://github.com/Fitriawan-Arya-N/todo-list-app.git'
            }
        }

        stage('SonarQube: Code Analysis') {
            steps {
                dir('todo-list-backend') {
                    withSonarQubeEnv('sonar-server') {
                        sh '''
                            $SCANNER_HOME/bin/sonar-scanner \
                            -Dsonar.projectName=todo-list-backend \
                            -Dsonar.projectKey=todo-list-backend \
                            -Dsonar.host.url=http://34.143.200.248:9000/ \
                            -Dsonar.login=${SONAR_AUTH_TOKEN}
                        '''
                    }
                }
            }
        }

        stage('Quality Check') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false
                }
            }
        }

        stage('Trivy File Scan') {
            steps {
                dir('todo-list-backend') {
                    sh 'trivy fs . > trivyfs.txt'
                }
            }
        }
        stage('Authenticate with GCP') {
            steps {
                withCredentials([file(credentialsId: 'gcp-service-account', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                    script {
                        sh '''#!/bin/bash
                        gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
                        gcloud config set project "${PROJECT_ID}"
                        gcloud config set compute/region "${GCP_REGION}"
                        gcloud config set compute/zone "${GCP_REGION}-a"
                        '''
                    }
                }
            }
        }
        stage('Docker Image Build') {
            steps {
                dir('todo-list-backend') {
                    script {
                        sh '''
                            docker rmi -f ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${GCP_GAR_REPO_BE_NAME}/${IMAGE_NAME}:${BUILD_NUMBER} || true
                            docker build -t ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${GCP_GAR_REPO_BE_NAME}/${IMAGE_NAME}:${BUILD_NUMBER} .
                        '''
                    }
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                script {
                    sh 'trivy image ${REPO_URL}/${IMAGE_NAME}:${BUILD_NUMBER} > trivyimage.txt' 
                }
            }
        }

        stage('Push Image to GAR') {
            steps {
                script {
                    sh '''
                        gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev
                        docker tag ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${GCP_GAR_REPO_BE_NAME}/${IMAGE_NAME}:${BUILD_NUMBER} ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${GCP_GAR_REPO_BE_NAME}/${IMAGE_NAME}:${BUILD_NUMBER}
                        docker push ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${GCP_GAR_REPO_BE_NAME}/${IMAGE_NAME}:${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Update Deployment File') {
            steps {
                dir('kubernetes-manifest-file/todo-list-backend') {
                    withCredentials([string(credentialsId: 'github-webhook-token', variable: 'GITHUB_TOKEN')]) {
                        script {
                            sh '''
                                git config user.email "${GITHUB_EMAIL}"
                                git config user.name "${GITHUB_USERNAME}"

                                # Mendapatkan tag image yang sedang digunakan
                                imageTag=$(grep -oP '(?<=todo-list-backend:)[^ ]+' deployment.yaml)
                                
                                # Mengganti tag image yang lama dengan tag build yang baru (BUILD_NUMBER)
                                sed -i "s/${imageTag}/todo-list-backend:${BUILD_NUMBER}/" deployment.yaml

                                # Menambahkan perubahan ke git, commit, dan push ke repo
                                git add deployment.yaml
                                git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                                git push https://${GITHUB_CRED}@github.com/${GITHUB_USERNAME}/${GITHUB_REPO_NAME}.git HEAD:main
                                
                                if [ $? -eq 0 ]; then
                                    echo "Git push successful"
                                else
                                    echo "Git push failed"
                                    exit 1
                                fi
                            '''
                        }
                    }
                }
            }
        }

    }
    post {
        always {
            echo 'Pipeline finished'
        }
        success {
            echo 'Pipeline finished successfully'
        }
        failure {
            echo 'Pipeline finished with failure'
        }
        unstable {
            echo 'Pipeline finished with unstable status'
        }
        cleanup {
            echo 'Cleaning up resources'
        }
    }
}
